version: '3.4'
services:

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env 
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${DATAROOT}/downloads:/downloads # downloads folder
      - ${DATAROOT}/complete/tv:/complete/tv # completed sonarr
      - ${DATAROOT}/complete/movies:/complete/movies # completed radarr
      - ${CONFIGROOT}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATAROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIGROOT}/config/jackett:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/config/sonarr:/config # config files
      - ${DATAROOT}/complete/tv:/tv # tv shows folder
      - ${DATAROOT}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/config/radarr:/config # config files
      - ${DATAROOT}/complete/movies:/movies # movies folder
      - ${DATAROOT}/downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: jaymoulin/plex:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${CONFIGROOT}/config/plex/db:/config # plex database
      - ${CONFIGROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${DATAROOT}/complete:/data # media library

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${DATAROOT}/complete/movies:/movies
      - ${DATAROOT}/complete/tv:/tv
    ports:
      - 6767:6767
